## 用nn函数算出来是错的

In [2]:
import numpy as np
import torch.nn as nn
import torch
import torch.nn.functional as F

In [3]:
m = nn.Conv2d(2, 1, 3, stride=1)

In [4]:
m.weight

Parameter containing:
tensor([[[[-0.0156,  0.0440, -0.1391],
          [ 0.1189,  0.0615, -0.2221],
          [-0.0245,  0.1586, -0.2049]],

         [[-0.1723,  0.0038,  0.1908],
          [ 0.1845, -0.2290, -0.0811],
          [-0.2066,  0.0974,  0.1042]]]], requires_grad=True)

In [5]:
m.bias

Parameter containing:
tensor([0.0875], requires_grad=True)

In [6]:
img = torch.randn(1,2,3,3)

In [7]:
img

tensor([[[[ 0.5160,  0.1288, -0.2415],
          [-1.3470, -0.0415, -0.5655],
          [-0.8501,  0.5800, -0.5635]],

         [[-0.0401,  0.8671, -0.3199],
          [ 1.3066, -0.9276, -0.3050],
          [-3.0326,  0.9111,  0.1247]]]])

In [8]:
m(img)

tensor([[[[1.4655]]]], grad_fn=<ThnnConv2DBackward>)

In [9]:
test1 = np.array([[-0.0156,  0.0440, -0.1391],
          [ 0.1189,  0.0615, -0.2221],
          [-0.0245,  0.1586, -0.2049]])
test2 = np.array([[-0.1723,  0.0038,  0.1908],
          [ 0.1845, -0.2290, -0.0811],
          [-0.2066,  0.0974,  0.1042]])

In [10]:
img1 = np.array([[ 0.5160,  0.1288, -0.2415],
          [-1.3470, -0.0415, -0.5655],
          [-0.8501,  0.5800, -0.5635]])
img2 = np.array([[-0.0401,  0.8671, -0.3199],
          [ 1.3066, -0.9276, -0.3050],
          [-3.0326,  0.9111,  0.1247]])

In [15]:
(test1.flatten() * img1.flatten()).sum()

-0.033435019999999996

In [16]:
(test2.flatten() * img2.flatten()).sum()

-0.21885754999999993

In [17]:
-0.033435019999999996-0.21885754999999993+0.0875

-0.16479256999999994

## 用F函数是对的

In [85]:
filters = torch.randn(1,2,3,3)
filters

tensor([[[[ 0.2429,  0.7151,  0.2877],
          [ 0.1758, -0.4354,  1.4375],
          [-1.1302, -0.5881, -1.2069]],

         [[ 1.2426,  1.3736, -0.1493],
          [ 1.0309,  0.0439,  0.1198],
          [-1.4130,  1.6267,  0.2951]]]])

In [86]:
inputs = torch.randn(1,2,3,3)
inputs

tensor([[[[ 1.5788,  0.0817, -2.0450],
          [-1.0694, -0.3810, -0.8863],
          [ 2.0288,  0.6449, -1.1850]],

         [[ 0.1782,  1.6458,  0.0079],
          [ 0.9727, -0.1143,  0.7050],
          [-1.7288,  0.9041, -0.7824]]]])

In [89]:
F.conv2d(inputs, filters)

tensor([[[[4.5611]]]])

In [90]:
test1 = np.array([[ 0.2429,  0.7151,  0.2877],
          [ 0.1758, -0.4354,  1.4375],
          [-1.1302, -0.5881, -1.2069]])
test2 = np.array([[ 1.2426,  1.3736, -0.1493],
          [ 1.0309,  0.0439,  0.1198],
          [-1.4130,  1.6267,  0.2951]])

In [91]:
img1 = np.array([[ 1.5788,  0.0817, -2.0450],
          [-1.0694, -0.3810, -0.8863],
          [ 2.0288,  0.6449, -1.1850]])
img2 = np.array([[ 0.1782,  1.6458,  0.0079],
          [ 0.9727, -0.1143,  0.7050],
          [-1.7288,  0.9041, -0.7824]])

In [92]:
(test1.flatten() * img1.flatten()).sum()

-2.6846406299999996

In [93]:
(test2.flatten() * img2.flatten()).sum()

7.24572802

In [96]:
7.24572802-2.6846406299999996

4.56108739