## numpy数组的常规操作有数组连接，劈分，展平，修改形状等操作

## 1. 数组连接 ：concatenate，stack，block
concatenate根据指定的维度，对一个元组、列表中的list或者ndarray进行连接，
不会增加维度。stack会按照选择的轴增加一个维度，实际使用的时候可以先把拼接后的形状写出来，然后再考虑合并后的数组是怎样的。
block是把一系列的块(通常是ndarray格式)构成的list合并成一个大矩阵，举个例子，一个矩阵均分为4块，再合并为一个大矩阵
只使用一句代码时可以使用这个函数，后面用例子具体说明。 

In [54]:
##stack
import numpy as np

a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('沿轴 0 堆叠两个数组：')
print (np.stack((a,b),0))
print ('\n')
 
print ('沿轴 1 堆叠两个数组：')
print (np.stack((a,b),1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [53]:
##numpy.concatenate((a1, a2, ...), axis)
a = [1,2,3]
b = [2,3,4]
print ('第一个数组：')
print(a)
print ('第二个数组：')
print(b)
print()
test = np.concatenate([a,b,b],axis=0)
print("concatenate 合并的矩阵为:")
print(test)
print()
print("concatenate不会新增维度，如果axis原数组中没有会报错")
np.concatenate([a,b,b],axis=1)

第一个数组：
[1, 2, 3]
第二个数组：
[2, 3, 4]

concatenate 合并的矩阵为:
[1 2 3 2 3 4 2 3 4]

concatenate不会新增维度，如果axis原数组中没有会报错


AxisError: axis 1 is out of bounds for array of dimension 1

In [55]:
##block是把一系列的块(通常是ndarray格式)构成的list合并成一个大矩阵，举个例子，一个矩阵均分为4块，再合并为一个大矩阵
##只使用一句代码时可以使用这个函数
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print ('第一个数组：')
print(a)
print ('第二个数组：')
print(a)
print ('第三个数组：')
print(b)
print ('第四个数组：')
print(b)
print()

print('使用concatenate不能一句代码合并这四个数组，合并结果为：')
test = np.concatenate([[a,a],[b,b]])
print(test)
print(f"数组形状为：{test.shape}")
print()
print('使用block一句代码合并这四个数组，合并结果为：')
test = np.block([[a,a],[b,b]])
print(test)
print(f"数组形状为：{test.shape}")

第一个数组：
[[1 2]
 [3 4]]
第二个数组：
[[1 2]
 [3 4]]
第三个数组：
[[5 6]
 [7 8]]
第四个数组：
[[5 6]
 [7 8]]

使用concatenate不能一句代码合并这四个数组，合并结果为：
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[5 6]
  [7 8]]]
数组形状为：(4, 2, 2)

使用block一句代码合并这四个数组，合并结果为：
[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]
 [7 8 7 8]]
数组形状为：(4, 4)


## 2. 数组劈分： split，hsplit, vsplit
split(array, int)或者split(array, list),list中定义切割的位置。
hsplit, vsplit和split用法一样

In [56]:
import numpy as np

a = np.arange(9)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('将数组分为三个大小相等的子数组：')
b = np.split(a,3)
print (b)
print ('\n')
 
print ('将数组在一维数组中表明的位置分割：')
b = np.split(a,[4,7])
print (b)

第一个数组：
[0 1 2 3 4 5 6 7 8]


将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


## 3. 展平操作: flat,flatten,ravel
flat返回一个数组元素迭代器， flatten()返回一份数组拷贝, ravel()修改会影响原始数组

In [57]:
import numpy as np
a = np.arange(9).reshape(3,3) 
print('原始数组是：')
print(a)
print()

print('修改flatten()后，原始数组没有影响：')
a.flatten()[0]=2
print(a)
print()

print('修改ravel()后，原始数组发生改变：')
a.ravel()[0]=2
print(a)

原始数组是：
[[0 1 2]
 [3 4 5]
 [6 7 8]]

修改flatten()后，原始数组没有影响：
[[0 1 2]
 [3 4 5]
 [6 7 8]]

修改ravel()后，原始数组发生改变：
[[2 1 2]
 [3 4 5]
 [6 7 8]]


## 4. 修改形状：numpy.reshape （
在一维，二维，三维的时候容易理解，当超过三维的时候就难理解一些，可以通过观察中括号[]的方式来理解）

In [58]:
import numpy as np
 
a = np.arange(8)
print ('原始数组：')
print (a)
print ('\n')

b = a.reshape(4,2)
print ('修改后的数组：')
print (b)

原始数组：
[0 1 2 3 4 5 6 7]


修改后的数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


## 5.转置： numpy.transpose 
函数用于对换数组的维度,transpose(1,2,0)

In [60]:
np.where?

In [61]:
test = np.arange(4).reshape(2,2)

In [62]:
np.where(test>1)

(array([1, 1]), array([0, 1]))

In [63]:
test[np.where(test>1)]

array([2, 3])