笔记参考：http://www.runoob.com/numpy/numpy-advanced-indexing.html
## 切片和索引
取出数组的一部分叫切片。索引是指按照一种数据结构快速查找数据的方式。
1. 可以通过冒号分隔切片参数 start:stop:step 来进行切片操作
2. 可以使用冒号：或者省略号...来取一个区间的元素

In [17]:
import numpy as np

In [18]:
##1. 通过冒号分隔切片参数 start:stop:step 来进行切片操作
a = np.arange(10)  
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
b

array([2, 4, 6])

In [31]:
##2. 可以使用冒号：或者省略号...来取一个区间的元素
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print()
print(':切割方式')
print(a[1:])
print(':切割方式2')
print(a[1:,:])
print('...切割方式')
print(a[1:,...])

[[1 2 3]
 [3 4 5]
 [4 5 6]]

:切割方式
[[3 4 5]
 [4 5 6]]
:切割方式2
[[3 4 5]
 [4 5 6]]
...切割方式
[[3 4 5]
 [4 5 6]]


## 高级索引

1. 使用array[数组x，数组y]的形式来进行索引，数组x(y)可以是一维或者多维数组，这种形式只能进行索引，不能切片，一维数组切割出来结果为一维，多维数组切割出来结果为多维度
2. 可以借助 : 或 … 进行切片
3. 布尔索引: 结果为一维数组
4. 花式索引：也是通过数组进行切片或者索引， 和1，2的区别是能够自定义切割结果的顺序(能够变换里面元素的位置)。 包括顺序索引数组，倒序索引数组，多个索引数组（要使用np.ix_）

In [41]:
##1. 使用array[数组x，数组y]的形式来进行索引，数组x(y)可以是一维或者多维数组，这种形式只能进行索引，不能切片。
import numpy as np 

x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：' )
print (x)
print()
print ('一维数组切割结果：')
y = x[[0,1,2],  [0,1,0]] 
print (y)
print()
print ('多维数组切割结果，这个数组的四个角元素是：')
rows = np.array([[0,0],[3,3]]) 
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols]  
print (y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

一维数组切割结果：
[0 4 6]

多维数组切割结果，这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


In [42]:
##2. 可以借助 : 或 … 进行切片
import numpy as np
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(a)
print()
b = a[1:3, 1:3]
c = a[1:3,[1,2]]
d = a[...,1:]
print(b)
print()
print(c)
print()
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[5 6]
 [8 9]]

[[5 6]
 [8 9]]

[[2 3]
 [5 6]
 [8 9]]


In [43]:
##3. 布尔索引: 结果为一维数组
import numpy as np 
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]


In [44]:
##4. 花式索引：也是通过数组进行切片或者索引， 和1，2的区别是能够自定义切割结果的顺序(能够变换里面元素的位置)。 包括顺序索引数组，倒序索引数组，多个索引数组（要使用np.ix_）
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print ('我们的数组是：')
print(x)
print()
print('顺序索引数组切割：')
print (x[[4,2,1,7]])

print()
print('倒序索引数组切割：')
print (x[[-4,-2,-1,-7]])
 
print()
print('多个索引数组切割：')
x=np.arange(32).reshape((8,4))
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

我们的数组是：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

顺序索引数组切割：
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]

倒序索引数组切割：
[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]

多个索引数组切割：
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
